### ISSUE TITLE
[Pandas Day-23]titanic.csv原始数据那里来？

### ISSUE THREAD

**Issue by heroye0919** [YZHANG1270/Girls-In-AI#43]
简洁有效的描述教程内出现的漏洞或问题。
只是想了解一下GIA Pandas Day-23的Titanic.csv的原始数据的来源？
描述你想实现的内容。
GIA Pandas Day-23的Titanic.csv 的原始数据的能否贴上去。

**Comment by YZHANG1270** [comment]
如果是按顺序学习的话，Day-21的作业就是Day-23的数据来源
