### ISSUE TITLE
如何成为一名AI算法工程师 链接建议优化

### ISSUE THREAD

**Issue by Yunkou** [YZHANG1270/Girls-In-AI#44]
建议优化 如何成为一名AI算法工程师 README.md 中的 「如何成为一名AI算法工程师」链接。
现在变成了微博下载客户端的倒流页面体验不是很好。

**Comment by YZHANG1270** [comment]
十分感谢提醒🙏已修正链接

**Comment by Yunkou** [comment]
@YZHANG1270  https://weibo.com/3340707810/GBryiyz3T url 贴这个 这样在电脑和手机都能正确的打开。 目前的地址，如果是电脑打开，会引导下载微博手机客户端。 亲测有效。

**Comment by YZHANG1270** [comment]
> @YZHANG1270 https://weibo.com/3340707810/GBryiyz3T url 贴这个 这样在电脑和手机都能正确的打开。 目前的地址，如果是电脑打开，会引导下载微博手机客户端。 亲测有效。

再次感谢！已修正👍
