### ISSUE TITLE
男的能学吗？

### ISSUE THREAD

**Issue by baagee** [YZHANG1270/Girls-In-AI#6]
**男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？**

**Comment by qingdoua** [comment]
当然能啊当然能啊当然能啊

**Comment by YZHANG1270** [comment]
> **男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？男的能学吗？**

当然可以，欢迎你来~
