### ISSUE TITLE
哪里可以看到课程？

### ISSUE THREAD

**Issue by cooleye** [YZHANG1270/Girls-In-AI#9]
https://codewithzhangyi.com 这个链接点进去
![image](https://user-images.githubusercontent.com/5831547/50803950-ec8f2580-1326-11e9-9f5a-69725e967854.png)

我应该从哪里进去，看到课程？

**Comment by YZHANG1270** [comment]
> https://codewithzhangyi.com 这个链接点进去
> ![image](https://user-images.githubusercontent.com/5831547/50803950-ec8f2580-1326-11e9-9f5a-69725e967854.png)
> 
> 我应该从哪里进去，看到课程？

请点击这个链接，进去有day-1/day-2/...字样的文件夹。这个是我们的ML-Diary系列的课程，正在不断更新中。链接：https://github.com/YZHANG1270/Girls-In-AI/tree/master/machine_learning_diary
